# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
  name = "test",
  srcs = ["Arduino.cpp"],
  hdrs = ["Arduino.h"],
  deps = [],
  strip_include_prefix = "",
  visibility = ["//visibility:public"]
)