# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
  name = "test",
  srcs = glob(["*.cpp"]),
  hdrs = glob(["*.h"]),
  deps = [],
  strip_include_prefix = "",
  visibility = ["//visibility:public"]
)