cc_library(
    name = "ina219",
    srcs = ["INA219.cpp"],
    hdrs = ["INA219.h", "INA.h"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
    deps = ["//lib/mock:mock"],
)