cc_library(
  name = "thermocouples",
  srcs = glob(["*.cpp"]),
  hdrs = glob(["*.h"]),
  strip_include_prefix = "",
  visibility = ["//visibility:public"],
  deps = [
    "//lib/mock:mock",
    "//lib/ADS1219:ADS1219",
    "//lib/ADS8167:ADS8167",
  ],
)