cc_library(
    name = "scheduler",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/mock:mock",
    ],
)